GithubActions: Transformando variaveis

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -2,147 +2,147 @@ name: Construir Infraestrutura AWS
 on:
     workflow_dispatch:
 jobs:
-    Infrastructure:
-      runs-on: ubuntu-latest
-      outputs:
-        db_host: ${{ steps.get_db_host.outputs.db_host }}
-        queue_url: ${{ steps.get_queue_url.outputs.queue_url }}
-      steps:
-          - name: Baixando arquivos do repo
-            uses: actions/checkout@v4
-          - name: Tokenizar artefatos
-            uses: cschleiden/replace-tokens@v1
-            with:
-              tokenPrefix: '___'
-              tokenSuffix: '___'
-              files: './*.tf'    
-            env:
-              AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
-          - name: Permissao arquivo
-            run: |
-              chmod +x ./modules/database/init/run_sql.sh
-              chmod +x ./modules/database/init/sql/1_inicializacao.sql
-          - name: Aws Credentials
-            uses: aws-actions/configure-aws-credentials@v4
-            with:
-              aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
-              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-              aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
-              aws-region: ${{ vars.AWS_REGION }}  
-          - name: Configurando Terraform
-            uses: hashicorp/setup-terraform@v3
-          - name: Terraform Init
-            run: terraform init -input=false
-          - name: Terraform Format
-            run: terraform fmt -check
-          - name: Terraform Validate
-            run: terraform validate
-          - name: Terraform Apply Database              
-            run: | 
-              valor=$((RANDOM % 90000000 + 10000000))
-              terraform apply -target=module.database -var="idSecret=$valor" -auto-approve
-          - name: Get Database Host
-            id: get_db_host
-            run: |
-              DB_HOST=$(terraform output -raw db_endpoint)
-              echo "::set-output name=db_host::${DB_HOST%%:*}"
-              echo "Database host: $DB_HOST"
-          - name: SQS             
-            run: terraform apply -target=module.sqs -auto-approve
-          - name: Get SQS Queue URL
-            id: get_queue_url
-            run: |
-              QUEUE_URL=$(terraform output -raw queue_url)
-              echo "::set-output name=queue_url::$QUEUE_URL"
-              echo "SQS Queue URL: $QUEUE_URL"
-          - name: S3
-            run: terraform apply -target=module.s3_bucket -auto-approve
-          - name: Terraform Apply EKS              
-            run: terraform apply -target=module.eks -var="id=${{ vars.AWS_ACCOUNT_ID}}" -auto-approve
-    K8S_Deploy:
-      needs: Infrastructure
-      outputs:
-        lb_video: ${{ steps.get_lb_video.outputs.lb_video }}
-        port_video: ${{ steps.get_lb_video.outputs.port_video }}
-        lb_usuario: ${{ steps.get_lb_usuario.outputs.lb_usuario }}
-        port_usuario: ${{ steps.get_lb_usuario.outputs.port_usuario }}
-      runs-on: ubuntu-latest
-      steps:
-        - name: Checkout Repo
-          uses: actions/checkout@v4       
-        - name: Tokenizar artefatos
-          uses: cschleiden/replace-tokens@v1
-          with:
-            tokenPrefix: '___'
-            tokenSuffix: '___'
-            files: './k8s/manifests/*.yml'    
-          env:
-            AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
-            AWS_REGION: ${{ vars.AWS_REGION }}
-            ACCESS_KEY: ${{ vars.AWS_ACCESS_KEY_ID }}
-            SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-            DB_HOST: ${{ needs.Infrastructure.outputs.db_host }}
-            QUEUE_URL: ${{ needs.Infrastructure.outputs.queue_url }}
-        - name: Configure AWS Credentials
-          uses: aws-actions/configure-aws-credentials@v4
-          with:
-            aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
-            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
-            aws-region: ${{ vars.AWS_REGION }}  
-        - name: Carregar Kube Config
-          run: |
-            aws eks update-kubeconfig \
-            --name ${{ vars.CLUSTER_NAME }} \
-            --region ${{ vars.AWS_REGION }}
-        - name: Verificar Configurações
-          run: | 
-            cat ./k8s/manifests/2-secret-bd.yml
-            cat ./k8s/manifests/1.1-configmap.yml
-        - name: Aplicar Configurações no EKS
-          run: kubectl apply -f ./k8s/manifests
-        - name: Aguardar Deployments
-          run: |
-            kubectl rollout status deployment/fiap-deployment-usuario -n fiap-soat11 --timeout=180s
-            kubectl rollout status deployment/fiap-deployment-video -n fiap-soat11 --timeout=180s
-        - name: Get Service LB usuario
-          id: get_lb_usuario
-          run: |
-              for i in {1..10}; do
-                LB=$(kubectl get svc fiap-svc-usuario -n fiap-soat11 -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
-                PORT=$(kubectl get svc fiap-svc-usuario -n fiap-soat11 -o jsonpath='{.spec.ports[0].port}')
-                if [ -n "$LB" ] && [ "$LB" != "<none>" ]; then
-                  echo "LoadBalancer hostname found: $LB"
-                  echo "::set-output name=lb_usuario::$LB"
-                  echo "::set-output name=port_usuario::$PORT"
-                  exit 0
-                else
-                  echo "Attempt $i: LoadBalancer hostname not available yet. Retrying in 30 seconds..."
-                  sleep 30
-                fi
-              done
-              echo "Failed to get LoadBalancer hostname after 10 attempts."
-              exit 1
-        - name: Get Service LB video
-          id: get_lb_video
-          run: |
-              for i in {1..10}; do
-                LB=$(kubectl get svc fiap-svc-video -n fiap-soat11 -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
-                PORT=$(kubectl get svc fiap-svc-video -n fiap-soat11 -o jsonpath='{.spec.ports[0].port}')
-                if [ -n "$LB" ] && [ "$LB" != "<none>" ]; then
-                  echo "LoadBalancer hostname found: $LB"
-                  echo "::set-output name=lb_video::$LB"
-                  echo "::set-output name=port_video::$PORT"
-                  exit 0
-                else
-                  echo "Attempt $i: LoadBalancer hostname not available yet. Retrying in 30 seconds..."
-                  sleep 30
-                fi
-              done
-              echo "Failed to get LoadBalancer hostname after 10 attempts."
-              exit 1
+    #Infrastructure:
+    #  runs-on: ubuntu-latest
+    #  outputs:
+    #    db_host: ${{ steps.get_db_host.outputs.db_host }}
+    #    queue_url: ${{ steps.get_queue_url.outputs.queue_url }}
+    #  steps:
+    #      - name: Baixando arquivos do repo
+    #        uses: actions/checkout@v4
+    #      - name: Tokenizar artefatos
+    #        uses: cschleiden/replace-tokens@v1
+    #        with:
+    #          tokenPrefix: '___'
+    #          tokenSuffix: '___'
+    #          files: './*.tf'    
+    #        env:
+    #          AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
+    #      - name: Permissao arquivo
+    #        run: |
+    #          chmod +x ./modules/database/init/run_sql.sh
+    #          chmod +x ./modules/database/init/sql/1_inicializacao.sql
+    #      - name: Aws Credentials
+    #        uses: aws-actions/configure-aws-credentials@v4
+    #        with:
+    #          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
+    #          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+    #          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
+    #          aws-region: ${{ vars.AWS_REGION }}  
+    #      - name: Configurando Terraform
+    #        uses: hashicorp/setup-terraform@v3
+    #      - name: Terraform Init
+    #        run: terraform init -input=false
+    #      - name: Terraform Format
+    #        run: terraform fmt -check
+    #      - name: Terraform Validate
+    #        run: terraform validate
+    #      - name: Terraform Apply Database              
+    #        run: | 
+    #          valor=$((RANDOM % 90000000 + 10000000))
+    #          terraform apply -target=module.database -var="idSecret=$valor" -auto-approve
+    #      - name: Get Database Host
+    #        id: get_db_host
+    #        run: |
+    #          DB_HOST=$(terraform output -raw db_endpoint)
+    #          echo "::set-output name=db_host::${DB_HOST%%:*}"
+    #          echo "Database host: $DB_HOST"
+    #      - name: SQS             
+    #        run: terraform apply -target=module.sqs -auto-approve
+    #      - name: Get SQS Queue URL
+    #        id: get_queue_url
+    #        run: |
+    #          QUEUE_URL=$(terraform output -raw queue_url)
+    #          echo "::set-output name=queue_url::$QUEUE_URL"
+    #          echo "SQS Queue URL: $QUEUE_URL"
+    #      - name: S3
+    #        run: terraform apply -target=module.s3_bucket -auto-approve
+    #      - name: Terraform Apply EKS              
+    #        run: terraform apply -target=module.eks -var="id=${{ vars.AWS_ACCOUNT_ID}}" -auto-approve
+    #K8S_Deploy:
+    #  needs: Infrastructure
+    #  outputs:
+    #    lb_video: ${{ steps.get_lb_video.outputs.lb_video }}
+    #    port_video: ${{ steps.get_lb_video.outputs.port_video }}
+    #    lb_usuario: ${{ steps.get_lb_usuario.outputs.lb_usuario }}
+    #    port_usuario: ${{ steps.get_lb_usuario.outputs.port_usuario }}
+    #  runs-on: ubuntu-latest
+    #  steps:
+    #    - name: Checkout Repo
+    #      uses: actions/checkout@v4       
+    #    - name: Tokenizar artefatos
+    #      uses: cschleiden/replace-tokens@v1
+    #      with:
+    #        tokenPrefix: '___'
+    #        tokenSuffix: '___'
+    #        files: './k8s/manifests/*.yml'    
+    #      env:
+    #        AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
+    #        AWS_REGION: ${{ vars.AWS_REGION }}
+    #        ACCESS_KEY: ${{ vars.AWS_ACCESS_KEY_ID }}
+    #        SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+    #        DB_HOST: ${{ needs.Infrastructure.outputs.db_host }}
+    #        QUEUE_URL: ${{ needs.Infrastructure.outputs.queue_url }}
+    #    - name: Configure AWS Credentials
+    #      uses: aws-actions/configure-aws-credentials@v4
+    #      with:
+    #        aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
+    #        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+    #        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
+    #        aws-region: ${{ vars.AWS_REGION }}  
+    #    - name: Carregar Kube Config
+    #      run: |
+    #        aws eks update-kubeconfig \
+    #        --name ${{ vars.CLUSTER_NAME }} \
+    #        --region ${{ vars.AWS_REGION }}
+    #    - name: Verificar Configurações
+    #      run: | 
+    #        cat ./k8s/manifests/2-secret-bd.yml
+    #        cat ./k8s/manifests/1.1-configmap.yml
+    #    - name: Aplicar Configurações no EKS
+    #      run: kubectl apply -f ./k8s/manifests
+    #    - name: Aguardar Deployments
+    #      run: |
+    #        kubectl rollout status deployment/fiap-deployment-usuario -n fiap-soat11 --timeout=180s
+    #        kubectl rollout status deployment/fiap-deployment-video -n fiap-soat11 --timeout=180s
+    #    - name: Get Service LB usuario
+    #      id: get_lb_usuario
+    #      run: |
+    #          for i in {1..10}; do
+    #            LB=$(kubectl get svc fiap-svc-usuario -n fiap-soat11 -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
+    #            PORT=$(kubectl get svc fiap-svc-usuario -n fiap-soat11 -o jsonpath='{.spec.ports[0].port}')
+    #            if [ -n "$LB" ] && [ "$LB" != "<none>" ]; then
+    #              echo "LoadBalancer hostname found: $LB"
+    #              echo "::set-output name=lb_usuario::$LB"
+    #              echo "::set-output name=port_usuario::$PORT"
+    #              exit 0
+    #            else
+    #              echo "Attempt $i: LoadBalancer hostname not available yet. Retrying in 30 seconds..."
+    #              sleep 30
+    #            fi
+    #          done
+    #          echo "Failed to get LoadBalancer hostname after 10 attempts."
+    #          exit 1
+    #    - name: Get Service LB video
+    #      id: get_lb_video
+    #      run: |
+    #          for i in {1..10}; do
+    #            LB=$(kubectl get svc fiap-svc-video -n fiap-soat11 -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
+    #            PORT=$(kubectl get svc fiap-svc-video -n fiap-soat11 -o jsonpath='{.spec.ports[0].port}')
+    #            if [ -n "$LB" ] && [ "$LB" != "<none>" ]; then
+    #              echo "LoadBalancer hostname found: $LB"
+    #              echo "::set-output name=lb_video::$LB"
+    #              echo "::set-output name=port_video::$PORT"
+    #              exit 0
+    #            else
+    #              echo "Attempt $i: LoadBalancer hostname not available yet. Retrying in 30 seconds..."
+    #              sleep 30
+    #            fi
+    #          done
+    #          echo "Failed to get LoadBalancer hostname after 10 attempts."
+    #          exit 1
     Api_Gateway:
-      needs: [Infrastructure, K8S_Deploy]
+      #needs: [Infrastructure, K8S_Deploy]
       runs-on: ubuntu-latest
       steps:
           - name: Baixando arquivos do repo
@@ -171,4 +171,5 @@ jobs:
           - name: Terraform Validate
             run: terraform validate
           - name: Terraform Apply
-            run: terraform apply -target=module.api_gateway -var="dns_eks_usuario=${{ needs.K8S_Deploy.outputs.lb_usuario }}:${{ needs.K8S_Deploy.outputs.port_usuario }}" -var="dns_eks_video=${{ needs.K8S_Deploy.outputs.lb_video }}:${{ needs.K8S_Deploy.outputs.port_video }}" -auto-approve
+            #run: terraform apply -target=module.api_gateway -var="dns_eks_usuario=${{ needs.K8S_Deploy.outputs.lb_usuario }}:${{ needs.K8S_Deploy.outputs.port_usuario }}" -var="dns_eks_video=${{ needs.K8S_Deploy.outputs.lb_video }}:${{ needs.K8S_Deploy.outputs.port_video }}" -auto-approve
+            run: terraform apply -target=module.api_gateway -var="dns_eks_usuario=a36484491763a41ce99b594ef42e68d0-1474956982.us-east-1.elb.amazonaws.com:8081" -var="dns_eks_video=a4c483238153647e9a9b87ed137b6154-814728418.us-east-1.elb.amazonaws.com:8082" -auto-approve
